dateModified: 1745333302
email:
  fromEmail: josh@artisandm.com
  fromName: 'Craft 5'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0a9bdd4a-4962-4983-ab37-ccbaa3aa62a3: Simple # Simple
    89139a46-f699-45f7-a220-6f7f98ff4d51: Default # Default
    a208ae0b-37d4-4720-9041-e8bc1acad32d: 'Craft 5' # Craft 5
    a7955212-18f3-4648-a7a4-faa98b6d5ee9: 'Craft 5' # Craft 5
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: WIDIKODINXIKHJGSTJO7SA78
    schemaVersion: 3.0.12
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Craft 5'
  schemaVersion: 5.7.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
